"""English titles and descriptions for the SERYTI abstract catalogue (milestone 1)."""
EN = {
 "LV-01": ("Free road, no lead vehicle", "The SDT drives alone in its lane: default behavior, speed keeping and lane centering."),
 "LV-02": ("Slower lead at constant speed", "The SDT closes in on a slower vehicle in its lane and switches to following."),
 "LV-03": ("Lead vehicle decelerates moderately", "The lead slows down without urgency; the SDT adjusts its gap."),
 "LV-04": ("Lead vehicle brakes hard", "The lead brakes sharply; the SDT must avoid a front collision."),
 "LV-05": ("Stopped lead vehicle (queue tail, stalled vehicle)", "A vehicle is stopped in the SDT lane."),
 "LV-06": ("Lead vehicle accelerates away", "The lead pulls away; the SDT resumes its set speed smoothly."),
 "LV-07": ("Stop-and-go traffic", "Dense traffic that slows down and speeds up again."),
 "LV-08": ("Erratic lead vehicle", "The lead brakes and accelerates unpredictably."),
 "LV-09": ("Motorcycle as lead vehicle", "Small vehicle ahead, harder to follow and to detect."),
 "LV-10": ("Truck lead hiding the road ahead", "A semi ahead hides a stopped vehicle further down the lane."),
 "LV-11": ("Lead vehicle cuts out and clears the lane", "The followed vehicle leaves the SDT lane with nothing behind it; the SDT resumes speed smoothly (Foretellix cut out)."),
 "CI-01": ("Cut-in from the left, sufficient gap", "A vehicle from the left lane moves in front of the SDT with a reasonable gap."),
 "CI-02": ("Tight cut-in from the left", "The vehicle cuts in very close in front of the SDT."),
 "CI-03": ("Cut-in from the right", "A vehicle from the right lane cuts in front of the SDT (SDT in the middle or left lane)."),
 "CI-04": ("Cut-in by a slower vehicle", "The vehicle cutting in drives slower than the SDT."),
 "CI-05": ("Cut-in by a semi-trailer", "A long combination vehicle cuts in front of the SDT."),
 "CI-06": ("Merge from the on-ramp ahead of the SDT", "A vehicle on the acceleration lane merges into the right lane where the SDT drives."),
 "CI-07": ("Brake check after a cut-in", "A vehicle that just cut in brakes sharply in front of the SDT."),
 "CI-08": ("Two vehicles cut in one after the other", "Two vehicles from the left lane cut in successively in front of the SDT (convoy variant of the Foretellix cut-in)."),
 "ADJ-01": ("Adjacent vehicle drifting toward the SDT", "A vehicle alongside leaves its lane toward the SDT."),
 "ADJ-02": ("Adjacent semi with swaying trailer", "The trailer of a neighbouring truck oscillates toward the SDT lane."),
 "ADJ-03": ("Motorcycle lane splitting", "A fast motorcycle passes between lanes alongside the SDT."),
 "ADJ-04": ("Fast and close overtake", "A vehicle passes the SDT very fast and very close."),
 "ADJ-05": ("Slow convoy in the adjacent lane", "The SDT passes a file of slow vehicles in the next lane (Foretellix slow neighbors). Risk: one vehicle pulls out in front of the SDT."),
 "ADJ-06": ("Adjacent lane hugger", "A neighbouring vehicle drives right on the marking on the SDT side without leaving its lane (Foretellix lane hugger): less lateral room, less time to see a cut-in."),
 "ADJ-07": ("Stopped queue in the adjacent lane", "The SDT passes a stopped file in the next lane (exit queue, crash, single-lane jam) (Foretellix stopped vehicles)."),
 "LC-NOM-01": ("Lane change into a free target lane", None),
 "LC-NOM-02": ("Lane change into a gap with surrounding traffic", None),
 "LC-NOM-03": ("Overtake a slow lead vehicle", None),
 "LC-NOM-04": ("Return to the lane after overtaking", None),
 "LC-TGT-01": ("Lane change with fast rear approach", None),
 "LC-TGT-02": ("Lane change with simultaneous merge from the far lane", None),
 "LC-TGT-03": ("Lane change with closing gap", None),
 "LC-TGT-04": ("Lane change with target lead braking", None),
 "LC-TGT-05": ("Lane change with vehicle alongside the trailer", None),
 "LC-TGT-06": ("Lane change with motorcycle in the blind spot", None),
 "LC-TGT-07": ("Lane change next to a large or unstable vehicle", None),
 "LC-CUR-01": ("Lane change with origin lead braking", None),
 "LC-CUR-02": ("Evasive lane change after lead cut-out", None),
 "LC-CUR-03": ("Lane change with tailgating follower", None),
 "RMP-01": ("Merge: gap accepted at the end of the acceleration lane", "The SDT is on the acceleration lane and must find a gap in the right lane."),
 "RMP-02": ("Merge: short acceleration lane", "The acceleration lane is too short to reach traffic speed."),
 "RMP-03": ("Merge: saturated main lane", "No gap: the SDT must stop or wait at the end of the acceleration lane (merge aborted outcome of SYSRQ-14124)."),
 "RMP-04": ("Merge: slow or stopped vehicle ahead on the ramp", "The vehicle ahead on the acceleration lane hesitates or stops."),
 "RMP-05": ("Merge: a main-lane vehicle moves over", "A vehicle in the right lane moves left to let the SDT in."),
 "RMP-06": ("Exit: queue on the off-ramp", "A queue backs up from the off-ramp into the deceleration lane."),
 "RMP-07": ("Missed exit for lack of gap", "Dense traffic in the exit lane: the SDT cannot reach it and must reroute (outcome of SYSRQ-14125)."),
 "RMP-08": ("Exit: tight ramp curve", "The ramp has a small radius: speed must be adapted before the curve."),
 "RMP-09": ("Vehicle crossing the gore at the last moment", "A vehicle crosses the SDT lane to catch the exit."),
 "RMP-10": ("Exit: vehicle reversing on the ramp", "A vehicle reverses on the ramp or the shoulder."),
 "RMP-11": ("Lead vehicle takes the exit", "The vehicle ahead slows down and takes the off-ramp on the right; the SDT continues straight (Foretellix cut-out to highway exit)."),
 "RMP-12": ("Convoy merging from the on-ramp", "Several vehicles merge from the acceleration lane ahead of or next to the SDT; the gaps let the SDT align within the convoy (Foretellix cars merge at highway entry)."),
 "RMP-13": ("SDT merges while a vehicle exits through the acceleration lane", "The SDT merges from the ramp; a right-lane vehicle crosses the acceleration lane to exit (weave, Foretellix DUT merges at highway entry)."),
 "RMP-14": ("Merge: curved and graded on-ramp", "The on-ramp curves and climbs or descends before the acceleration lane: the SDT must hold its path and speed before merging (gap found from HIRE v2: On-Ramp Merge, H5)."),
 "LC-RD-01": ("Mandatory lane change at a lane drop", None),
 "LC-RD-02": ("Lane change in a work zone lane closure", None),
 "LC-RD-03": ("Lane change in a weave section", None),
 "LC-RD-04": ("Mandatory lane change for an exit", None),
 "LC-RD-05": ("Lane change to yield to merging traffic", None),
 "LC-RD-06": ("Lane change with degraded lane markings", None),
 "LC-RD-07": ("Lane change on a curve or grade", None),
 "LC-RD-08": ("Lane change with map lane mismatch", None),
 "RD-09": ("Lane narrower than 3.5 m", "Lane width drops below the Cruise and Stay in Lane entry threshold (3.5 m)."),
 "RD-10": ("Speed limit change", "The limit drops (zone, work zone, temporary sign); the SDT must comply."),
 "RD-11": ("No shoulder (bridge, viaduct)", "No room to stop outside the lane when a stop is requested."),
 "RD-12": ("Crosswind gust", "Exposed section with strong wind and gusts."),
 "RD-13": ("Steep downhill with heavy load", "Downhill grade that lengthens stopping distances."),
 "RD-14": ("Curve with a vehicle in the next lane", "The SDT follows a curve while a vehicle drives ahead or alongside in the next lane; a neighbouring semi may off-track inward (Foretellix to side on curve)."),
 "EMV-03": ("Emergency vehicle in congestion", "An ambulance moves up through slow traffic: a path must be opened."),
 "EMV-04": ("Police vehicle following the SDT for more than 20 s", "A LEO follows the SDT with lights on: pull to the shoulder requested."),
 "EMV-05": ("Emergency vehicle stopped in the lane", "A response vehicle blocks the SDT lane."),
 "EMV-06": ("Police pursuit passing the SDT", "A police vehicle passes at high speed."),
 "LC-OOD-01": ("Move over for a stopped EMV on the shoulder", None),
 "LC-OOD-02": ("Yield the lane to an approaching EMV", None),
 "LC-OOD-03": ("Lane change with an object in the target lane", None),
 "LC-OOD-04": ("Lane change at a crash scene", None),
 "LC-REF-01": ("Vehicle stopped on the shoulder (reference case)", "A vehicle is stopped fully on the right shoulder while the SDT drives in the right lane. Vehicles ahead and behind may be present. Manual reference of milestone 1."),
 "OBJ-01": ("Small drivable debris in the lane", "Low debris in the SDT lane: straddle it or avoid it."),
 "OBJ-02": ("Lost cargo or large debris in the lane", "A non-drivable object blocks the SDT lane."),
 "OBJ-03": ("Broken-down vehicle overlapping from the shoulder", "A vehicle stopped on the shoulder encroaches on the right lane."),
 "OBJ-04": ("Animal on the roadway", "Deer or livestock on the lane (outside the validated ODD)."),
 "OBJ-05": ("Pedestrian on the highway", "A person out of a broken-down vehicle walks near the lane."),
 "OBJ-06": ("Object appearing suddenly near the SDT", "Debris dropped or thrown by a vehicle, discovered late."),
 "AB-01": ("Wrong-way driver", "A vehicle comes the opposite way in the SDT lane."),
 "AB-02": ("Tailgating follower", "A vehicle sits very close behind the SDT: any braking becomes risky."),
 "AB-03": ("Vehicle driving on the shoulder", "A vehicle passes on the shoulder."),
 "LC-ABT-01": ("Lane change abort and return", None),
 "LC-ABT-02": ("Lane change interrupted by DDT fallback", None),
 "FB-01": ("System degradation, shoulder available", "A degradation requires leaving the lane and stopping on the shoulder."),
 "FB-02": ("System degradation, no usable shoulder", "The degradation requires a stop while no shoulder can be used."),
 "FB-03": ("Shoulder occupied at the planned stop point", "A vehicle is already stopped where the SDT wanted to stop (shoulder blocked outcome of SYSRQ-14127)."),
 "FB-04": ("Stop in lane with a fast follower", "The SDT stops in lane while a vehicle approaches fast from behind."),
 "FB-05": ("Emergency lateral avoidance, adjacent lane free", "Obstacle found late, the next lane is free."),
 "FB-06": ("Emergency lateral avoidance, adjacent lane occupied", "Obstacle found late, a vehicle occupies the next lane."),
 "FB-07": ("Remote stop-in-lane command (HICD)", "An operator requests a stop in lane (MRM-E)."),
 "FB-08": ("Resume driving after a shoulder stop", "The SDT leaves the shoulder and merges into traffic."),
 "URB-01": ("Green light, going straight", "The SDT crosses a signalized intersection on green."),
 "URB-02": ("Red-light runner", "A crossing vehicle runs the red light while the SDT crosses."),
 "URB-03": ("All-way stop, ambiguous arrival order", "Several vehicles arrive at the same time at a stop."),
 "URB-04": ("Unprotected left turn with oncoming traffic", "The SDT turns left across an oncoming flow."),
 "URB-05": ("Right turn with pedestrian on the crosswalk", "A pedestrian crosses the street the SDT turns into."),
 "URB-06": ("Right turn: trailer sweeps the curb, cyclist on the right", "The trailer sweep threatens a cyclist or the sidewalk."),
 "URB-07": ("Cross traffic at an uncontrolled intersection", "A crossing vehicle does not yield."),
 "URB-08": ("Pedestrian waiting at or entering a crosswalk", "A pedestrian at the edge of or on the crosswalk."),
 "URB-09": ("Pedestrian hidden by a parked vehicle", "A pedestrian steps out from behind a parked vehicle."),
 "URB-10": ("Cyclist in the lane", "The SDT catches up with a cyclist riding in its lane."),
 "URB-11": ("Vehicle pulling out of a parking space", "A vehicle parked on the right pulls out in front of the SDT."),
 "URB-12": ("Double-parked vehicle blocking the lane", "A stopped vehicle occupies the SDT lane."),
 "URB-13": ("Bus stopping at a bus stop", "The bus ahead stops to pick up passengers."),
 "URB-14": ("Emergency vehicle at an intersection", "An emergency vehicle crosses or comes the other way at an intersection."),
 "URB-15": ("Oncoming vehicle crossing the center line", "An oncoming vehicle crosses the center line."),
 "URB-16": ("Vehicle ahead turning and slowing", "The vehicle ahead slows down to turn."),
 "HUB-01": ("Yard tractor crossing the path", "A yard tractor crosses in front of the SDT at low speed."),
 "HUB-02": ("Worker on foot in the yard", "An operator on foot near the SDT path."),
 "HUB-03": ("Reverse docking with an obstacle", "An obstacle is behind the trailer while docking."),
 "HUB-04": ("Misalignment at the dock", "The trailer arrives at an angle to the dock."),
 "HUB-05": ("Leaving the dock with cross traffic", "The SDT leaves the dock while a vehicle drives in the aisle."),
 "HUB-06": ("Parked trailer encroaching on the aisle", "A badly parked trailer reduces the passing space."),
 "HUB-07": ("Forklift crossing", "A forklift crosses or reverses in front of the SDT."),
 "HUB-08": ("Queue at the exit gate", "Vehicles wait at the gate when the SDT departs."),
 "HUB-09": ("Tight turn in the yard", "The trailer sweep grazes an obstacle."),
}
FAMILIES = {
 "LV": ("Lead vehicle", "What the vehicle ahead does: slower, brakes, stops, accelerates."),
 "CI": ("Cut-in", "A vehicle enters the SDT lane ahead of it."),
 "ADJ": ("Adjacent vehicles", "A vehicle in a neighbouring lane closes in, drifts or passes."),
 "LC-NOM": ("Nominal lane change", "The SDT changes lane by choice."),
 "LC-TGT": ("Target lane traffic", "What makes the target-lane gap safe or not."),
 "LC-CUR": ("Origin lane event during the lane change", ""),
 "RMP": ("Ramps: merge, exit, weave", ""),
 "LC-RD": ("Road-imposed lane change", "Lane drop, work zone, exit, markings, curve, map."),
 "RD": ("Road and infrastructure", "Lane width, speed limit, shoulder, wind, grade."),
 "EMV": ("Emergency vehicles", ""),
 "LC-OOD": ("Out-of-ODD events requiring a lane change", ""),
 "OBJ": ("Unexpected objects and road users", ""),
 "AB": ("Abnormal behavior of other road users", ""),
 "LC-ABT": ("Abort and fallback during a lane change", ""),
 "FB": ("Fallback and MRM (DDT fallback)", ""),
 "URB": ("Urban situations", "Intersections, pedestrians, cyclists."),
 "HUB": ("Hub situations", "Yard, dock, shared spaces."),
}
