# Lane Change scenario library, Foretellix-style. Content data (PROPOSED).
# Slot model follows Torc Miro "Concrete Scenario A/B":
#   SDT in origin lane. A = lead in origin lane, B = lead in target lane,
#   C = follower in origin lane, D = follower in target lane,
#   E = vehicle in the lane beyond the target lane (beside / behind SDT),
#   F = vehicle in the lane beyond the target lane (ahead of SDT),
#   G = vehicle in the lane on the other side of the origin lane,
#   S = shoulder object / vehicle, O = static object in a lane.

SLOTS = [
    ("SDT", "Ego (system under test)", "Origin lane", "Torc SDT, tractor + 53 ft trailer (~22 m combination). Performs the lane change."),
    ("A", "Lead, origin lane", "Origin lane, ahead", "Vehicle directly ahead of SDT in the origin lane. Miro Concrete A/B: vehicle A."),
    ("B", "Lead, target lane", "Target lane, ahead", "Front boundary of the gap SDT moves into. Miro Concrete B: Torc lead vehicle when run on public road."),
    ("C", "Follower, origin lane", "Origin lane, behind", "Vehicle behind SDT in the origin lane."),
    ("D", "Follower, target lane", "Target lane, behind", "Rear boundary of the gap SDT moves into. Miro Concrete B: Torc chase vehicle when run on public road."),
    ("E", "Far-lane vehicle, beside / behind", "Lane beyond target lane, beside or behind SDT", "Can merge into the same target lane as SDT (Miro Concrete B, vehicle E)."),
    ("F", "Far-lane vehicle, ahead", "Lane beyond target lane, ahead", "Can cut into the target-lane gap ahead of SDT."),
    ("G", "Other-side adjacent vehicle", "Lane on the opposite side of the origin lane", "Only relevant when SDT is in a middle lane."),
    ("S", "Shoulder actor / object", "Shoulder adjacent to SDT lanes", "Stopped EMV, disabled vehicle, workers, debris on shoulder."),
    ("O", "Static object in lane", "Target or origin lane", "FOD, lost cargo, stopped vehicle, channelizing devices."),
]

# Solution-independent task chain (answers the Miro sticky "Don't have Tasks").
TASKS = [
    ("T1", "Perceive road users around SDT in all slots (A to G, S, O), including the trailer-side blind zone",
     "Raw sensor data (camera, lidar, radar), trailer state",
     "Object list: position, velocity, class, existence confidence, per slot",
     "Detection range per slot vs required range (rear: closing speed x decision horizon); missed-detection rate per slot and per actor kind (motorcycle, low-contrast car); position error; velocity error; latency; track continuity during occlusion",
     "FI-SEN-01, FI-SEN-02, FI-SEN-08, FI-PCP-06, FI-PCP-07, FI-PCP-08, FI-PCP-09, FI-PCP-10, FI-PCP-12, FI-PCP-16, FI-PCP-17, FI-PCP-18, FI-AIM-01, FI-AIM-04"),
    ("T2", "Estimate lane geometry and the existence, type and legal availability of the target lane",
     "Perception lane features, HD map, localization",
     "Lane model, lane count, boundary type (dashed / solid), restrictions (gore, work zone, lane drop)",
     "Lateral boundary error; boundary-type classification accuracy (dashed vs solid); target-lane existence correctness; map vs perception consistency rate; ego lane assignment correctness",
     "FI-PCP-01, FI-PCP-02, FI-PCP-03, FI-PCP-04, FI-PCP-05, FI-PCP-14, FI-LOC-04, FI-LOC-05"),
    ("T3", "Predict intent and trajectories of relevant actors (B, D, E, F, A)",
     "Object list, lane model, signal states of other vehicles",
     "Predicted trajectories with uncertainty, lane-change intent of other actors",
     "Intent detection lead time (E merging, D accelerating); trajectory error at 3 s and 5 s; missed / false lane-change-intent rate",
     "FI-VI-04, FI-AIM-04, FI-PCP-09"),
    ("T4", "Decide that a lane change is needed (route, efficiency, courtesy, move-over, lane drop)",
     "Route, lane model, traffic state, rules",
     "Lane-change request with side, urgency and deadline (distance / time)",
     "Decision lead distance before mandatory point (lane drop, exit, work zone taper); unnecessary lane-change rate; missed mandatory lane change rate",
     "FI-VI-05, FI-PCP-14, FI-LOC-04"),
    ("T5", "Assess gap and feasibility (front and rear gap in target lane, imposed deceleration on D, own capability with load)",
     "Predicted trajectories, lane model, own capability envelope",
     "Go / no-go, selected gap, target speed profile",
     "Unsafe-gap acceptance rate (false accept); safe-gap rejection rate (false reject, efficiency); margin to threshold at decision time",
     "FI-VI-05, FI-VI-07, FI-VI-04"),
    ("T6", "Communicate intent (turn signal timing, side, continuity, cancel)",
     "Go decision, maneuver state",
     "Turn signal command",
     "Signal lead time before lateral motion; continuity until lane change completed; correct side; cancel after completion or abort; signal conspicuity to followers",
     "Communicate Intent function (HAZOP rows 169, 174); TC-CRAWL-273 to 277 (ego conspicuity)"),
    ("T7", "Plan the lane-change trajectory, including trailer swept path",
     "Selected gap, lane model, capability envelope",
     "Trajectory (lateral and longitudinal)",
     "Swept-path clearance to adjacent actors and boundaries; peak lateral acceleration and jerk; feasibility vs capability (load, grade, adhesion)",
     "FI-VI-01, FI-VI-02, FI-VI-07, FI-PCP-16"),
    ("T8", "Execute and monitor; decide continue vs abort (point of no return)",
     "Updated object list and predictions during maneuver",
     "Continue / abort decision, return trajectory",
     "Abort decision latency after trigger; time spent straddling the boundary; correctness of continue-vs-abort decision per phase",
     "FI-VI-06, FI-VI-04, FI-PCP-07"),
    ("T9", "Control the vehicle along the trajectory (lateral and longitudinal tracking, stability)",
     "Trajectory, vehicle state",
     "Steering, acceleration, deceleration commands",
     "Lateral tracking error; trailer off-tracking; stability margins (roll, yaw) under wind, curvature, grade",
     "FI-VI-07, FI-SEN-07 (control feedback)"),
    ("T10", "Complete and stabilize: center in target lane, cancel signal, re-establish following gap",
     "Vehicle state, object list",
     "Steady lane keeping, following distance restored",
     "Time to re-center; headway to new lead (B) after completion; signal cancelled",
     "FI-PCP-04, FI-VI-01"),
]

# Evaluation KPIs and checkers (scenario level), grouped by Torc Behavior Table categories.
KPIS = [
    ("K-SAF-01", "Safety", "no_collision", "No contact between SDT (tractor or trailer) and any actor or object", "bool", "Must be true", "Checker"),
    ("K-SAF-02", "Safety", "sdt_min_ttc_to_vehicle", "Minimum time-to-collision between SDT and any actor during the scenario", "s", "TBD (acceptance criteria, ISO 21448 Cl.6 gap)", "KPI"),
    ("K-SAF-03", "Safety", "sdt_min_mttc_to_vehicle", "Minimum modified TTC (accounts for acceleration)", "s", "TBD", "KPI"),
    ("K-SAF-04", "Safety", "min_lateral_clearance", "Minimum lateral distance between SDT swept path (incl. trailer) and adjacent actors", "m", "TBD", "KPI"),
    ("K-SAF-05", "Safety", "imposed_decel_on_rear_target_vehicle", "Deceleration that vehicle D must apply because of the SDT lane change", "m/s2", "Candidate: <= 3 m/s2 (UN R79 / R157 lane-change criterion, to verify)", "KPI + checker"),
    ("K-SAF-06", "Safety", "time_headway_to_new_lead_after_lc", "Time headway SDT to B once lane change is completed", "s", "TBD", "KPI"),
    ("K-SAF-07", "Safety", "boundary_straddle_duration", "Time the SDT occupies two lanes", "s", "TBD", "KPI"),
    ("K-SAF-08", "Safety", "abort_decision_correct", "When a trigger appears, SDT chooses the safer of continue / abort for the current phase", "bool", "Must be true", "Checker"),
    ("K-CMP-01", "Traffic compliance", "signal_before_lateral_motion", "Turn signal active before lateral motion starts, and lead time", "bool / s", "Signal required (TX TRC 545.104); lead time TBD (candidate from UN R79 / R157, to verify)", "Checker + KPI"),
    ("K-CMP-02", "Traffic compliance", "lc_made_safely", "Lane left only when movement can be made safely (TX TRC 545.060)", "bool", "Must be true", "Checker"),
    ("K-CMP-03", "Traffic compliance", "no_lc_across_prohibited_marking", "No lane change across solid line, gore, or work-zone restricted marking", "bool", "Must be true", "Checker"),
    ("K-CMP-04", "Traffic compliance", "move_over_compliance", "Vacate lane next to stopped EMV / TxDOT / tow vehicle, or slow 20 mph below limit (TX TRC 545.157)", "bool", "Must be true", "Checker"),
    ("K-CMP-05", "Traffic compliance", "pass_and_return_when_clear", "After overtaking, return only when safely clear of the overtaken vehicle (TX TRC 545.053)", "bool", "Must be true", "Checker"),
    ("K-EFF-01", "Efficiency", "lc_completed", "SDT reached the target lane when the lane change was needed and feasible", "bool", "Must be true for mandatory LC before deadline", "KPI"),
    ("K-EFF-02", "Efficiency", "lc_duration", "Time from lateral motion start to centered in target lane", "s", "TBD", "KPI"),
    ("K-EFF-03", "Efficiency", "aborted_attempts", "Number of aborted lane-change attempts", "count", "TBD", "KPI"),
    ("K-EFF-04", "Efficiency", "speed_loss", "Speed lost vs desired speed due to the lane change or its delay", "mph", "TBD", "KPI"),
    ("K-CRT-01", "Courtesy", "max_lateral_accel_and_jerk", "Peak lateral acceleration and jerk of SDT", "m/s2, m/s3", "TBD", "KPI"),
    ("K-CRT-02", "Courtesy", "no_forced_braking_of_others", "No other actor brakes harder than a comfort threshold because of SDT", "bool", "Candidate threshold TBD", "Checker"),
    ("K-CRT-03", "Courtesy", "yield_to_merging_traffic", "SDT moves over or adjusts speed to let on-ramp traffic merge when possible", "bool", "Should be true when feasible", "KPI"),
]

# Parameters: logical ranges. status = ODD-quantified | proposed | GAP
PARAMS = [
    ("sdt_speed", "SDT speed at lane-change start", "mph", "45 .. 75", "ODD-quantified", "Speed Limit TORC-ODD-84: observed 10..75 mph on crawl routes; 70 and 75 mph = 94.4% of miles. Spec range 45..80 mph."),
    ("lc_side", "Lane-change direction", "enum", "left, right", "proposed", "Both directions are legal on I-35 multi-lane sections (passing on the right allowed when safe, TX TRC 545.057)."),
    ("lane_count", "Number of lanes in SDT direction", "count", "2 .. 4", "ODD-quantified", "Lane Count TORC-ODD-356: 1 lane 3.7%, 2 lanes 49.7%, 3 lanes 39.1%, 4 lanes 7.5% of miles. LC needs >= 2."),
    ("origin_lane_index", "SDT lane position", "enum", "rightmost, middle, leftmost", "proposed", "Middle lane only when lane_count >= 3 (46.6% of miles)."),
    ("lane_width", "Lane width", "m", "2.5 .. 6.5 (nominal 3.5 .. 3.75)", "ODD-quantified", "Lane Width TORC-ODD-76 (HD map): 85.7% of miles in 3.5..3.75 m bin; < 3.25 m about 0.1%."),
    ("curvature", "Horizontal curvature at LC location", "1/m", "0 .. 0.0022 (spec)", "ODD-quantified", "Curvature TORC-ODD-360: 98.3% straight; observed max 0.25 1/m (likely ramps, to confirm) vs spec max 2.2e-3."),
    ("grade", "Longitudinal slope", "%", "-8 .. +8", "ODD-quantified", "Slope TORC-ODD-79: observed -8..+8% vs spec +/-6% (discrepancy to raise)."),
    ("traffic_volume", "Hourly vehicle volume", "veh/h", "303 .. 1950", "ODD-quantified", "TCDS via ODD report: 303.2..1950 veh/h."),
    ("actor_kind", "Kind of each actor", "list", "passenger car, pickup, motorcycle, tractor-trailer, wide load, EMV, towed vehicle", "proposed", "Mirrors Foretellix 'kinds' parameter. Kinds from TC catalogue L4 (TC-CRAWL-168..201)."),
    ("actor_speed_rel_to_sdt", "Speed of actor minus SDT speed", "mph", "-20 .. +30 (proposed)", "GAP", "No L4 kinematics on I-35 yet (relative speed distribution per lane). Needs TCDS per-lane speeds / TU enrichment."),
    ("front_gap_target_lane", "Time gap SDT to B at LC start", "s", "0.5 .. 6 (proposed)", "GAP", "Gap distribution in target lane not characterized (L4 gap)."),
    ("rear_gap_target_lane", "Time gap D to SDT rear at LC start", "s", "0.5 .. 6 (proposed)", "GAP", "Same: L4 gap acceptance data missing."),
    ("rear_closing_speed", "Closing speed of D on SDT", "mph", "0 .. 30 (proposed)", "GAP", "Fast-approach frequency unknown on corridor."),
    ("actor_long_decel", "Deceleration of braking actor (A or B)", "m/s2", "1 .. 8 (proposed)", "proposed", "Generic range from mild to emergency braking; corridor-specific data not available."),
    ("actor_lc_start_time_rel_to_sdt", "Start of actor lane change relative to SDT lateral motion start", "s", "-2 .. +3 (proposed)", "proposed", "Drives the simultaneous-merge and cut-in families."),
    ("actor_lateral_speed", "Lateral speed of merging / cutting-in actor", "m/s", "0.3 .. 1.5 (proposed)", "GAP", "Cut-in / cut-out rates and dynamics: identified L4 gap (TCDS, CRIS)."),
    ("distance_to_mandatory_point", "Distance from LC start to lane drop / exit / taper", "m", "100 .. 1600 (proposed)", "proposed", "From map per site; work zones not in HD map yet (Work Zones TORC-FLD-1569 empty in report)."),
    ("marking_quality", "Lane boundary condition", "enum", "good, faded, missing, double exposure, temporary", "GAP", "Lane Boundary TORC-FLD-1588 has no values in ODD report."),
    ("rain", "Precipitation", "enum", "dry 87.8%, light 10.8%, moderate 1.1%, heavy 0.24%", "ODD-quantified", "Rain TORC-ODD-27 (ERA5 hourly)."),
    ("wind", "Wind class", "enum", "calm .. near gale (fresh breeze and above 1.4%)", "ODD-quantified", "Wind TORC-FLD-1559 (ERA5)."),
    ("sun_azimuth_vs_heading", "Sun position relative to SDT heading", "enum", "SE 62.0%, S 30.3%, SW 4.8%, E 2.2%", "ODD-quantified", "Sun Angle TORC-ODD-36 (NOAA vs route headings)."),
    ("light", "Light condition", "enum", "day, dawn / dusk, night", "proposed", "Solar radiation 0 W/m2 for 58.8% of hours (night) in ODD report."),
]

# Modifiers: mixable on top of any compatible scenario (Foretellix "mix").
MODIFIERS = [
    ("M-01", "Rain light / moderate / heavy", "Rain TORC-ODD-27", "Reduces sensor range and adhesion: larger gaps, longer LC", "TC-CRAWL-247, TC-CRAWL-248, TC-CRAWL-250", "All"),
    ("M-02", "Spray plume from trucks", "Rain TORC-ODD-27", "Occludes B, D, E when they are trucks", "TC-CRAWL-249, TC-CRAWL-274", "All with truck actors"),
    ("M-03", "Crosswind / gusts", "Wind TORC-FLD-1559", "Lateral disturbance during lateral motion; trailer stability", "TC-CRAWL-225, TC-CRAWL-226, TC-CRAWL-227, TC-CRAWL-228", "All"),
    ("M-04", "Low sun / glare", "Sun Angle TORC-ODD-36", "Camera degradation, washed-out signals of others and of SDT", "TC-CRAWL-219, TC-CRAWL-184, TC-CRAWL-273", "All"),
    ("M-05", "Night / low light", "Light (derived)", "Reduced passive detectability, markings invisible", "TC-CRAWL-217, TC-CRAWL-231, TC-CRAWL-058", "All"),
    ("M-06", "Dense traffic", "Vehicles TORC-FLD-30123 (TCDS volume)", "Smaller gaps, more actors in slots, occlusion", "TC-CRAWL-173, TC-CRAWL-186", "All"),
    ("M-07", "Heat shimmer", "Air Temperature TORC-ODD-15", "Distorted camera returns at range", "TC-CRAWL-252, TC-CRAWL-251", "All"),
    ("M-08", "Narrow lane", "Lane Width TORC-ODD-76", "Less lateral clearance for the trailer", "TC-CRAWL-027, TC-CRAWL-044", "All"),
    ("M-09", "Curve / grade", "Curvature TORC-ODD-360, Slope TORC-ODD-79", "Sight distance, stability, stopping distance", "TC-CRAWL-032, TC-CRAWL-034, TC-CRAWL-039, TC-CRAWL-042", "All"),
    ("M-10", "Sensor soiling / misalignment", "L0 vehicle state", "Degraded detection on one side", "TC-CRAWL-011, TC-CRAWL-012, TC-CRAWL-013", "All"),
    ("M-11", "Low-contrast / low-reflectivity actor", "Vehicles TORC-FLD-30123", "Under-detection of the actor in the key slot", "TC-CRAWL-168, TC-CRAWL-169, TC-CRAWL-193", "All"),
]

FAMILIES = [
    ("LC-NOM", "Nominal discretionary lane change", "SDT changes lane because it wants to (overtake, lane preference). Torc Miro 'Abstract Scenario' and 'Concrete A' live here."),
    ("LC-TGT", "Conflicts in the target lane", "Something in or entering the target lane makes the gap unsafe: fast rear approach, competing merge (Miro Concrete B), closing gap, blind-spot actors."),
    ("LC-CUR", "Events in the origin lane during the lane change", "A or C changes the situation while SDT is preparing or executing."),
    ("LC-RD", "Road-structure driven lane change", "Lane drop, work zone, weave, exit, merge courtesy, degraded markings, curve / grade, map mismatch. Often mandatory with a deadline."),
    ("LC-ABT", "Abort and fallback during lane change", "SDT must return to the origin lane or hand over to MRM mid-maneuver. Link to the September MRM scope."),
    ("LC-OOD", "Out-of-ODD events requiring a lane change", "Move-over for EMV, stopped vehicle, FOD, crash scene. Tagged [Out-of-ODD] where the element is not a validated ODD element."),
]

STD_PHASES_DISC = "init_drive > signal > change_lane > post_phase"

# Each scenario: dict
S = []
def sc(**k): S.append(k)

sc(id="LC-NOM-01", fam="LC-NOM", name="sut_lane_change_free_target_lane",
   torc="Miro 'Abstract Scenario'",
   desc="SDT changes lane into an empty target lane. Ego-only reference scenario.",
   lc_type="Discretionary", side="left / right",
   actors="none",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2 (TORC-ODD-356); dashed boundary (TORC-FLD-1588); Lane Width (TORC-ODD-76)",
   params="sdt_speed, lc_side, lane_count, origin_lane_index, lane_width, curvature, grade",
   variants="left vs right; middle lane start",
   wanted="Signal before lateral motion and keep it until completed; move only across a dashed boundary; smooth lateral profile within comfort limits; center in target lane and cancel signal.",
   tasks="T2, T4, T6, T7, T9, T10",
   cov="sdt_speed_at_change_lane [45..75 mph, 5 mph]; lc_side [left, right]; lane_count [2,3,4]; lc_duration [0..10 s, 1 s]; signal_lead_time [0..5 s, 0.5 s]",
   kpis="K-SAF-01, K-SAF-07, K-CMP-01, K-CMP-03, K-EFF-02, K-CRT-01",
   mods="M-01, M-03, M-04, M-05, M-08, M-09, M-10",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance", "Signal intent for maneuver", "Misleading signal (not needed)", "Vehicle stability"],
   tcs="TC-CRAWL-055, TC-CRAWL-060, TC-CRAWL-067, TC-CRAWL-068, TC-CRAWL-225, TC-CRAWL-227",
   env="Simulation, then track",
   fx="sut_cut_out (public Foretellix evaluation scenario: ego leaves lane behind a lead) is the closest analog with a lead added")

sc(id="LC-NOM-02", fam="LC-NOM", name="sut_lane_change_into_gap_with_surrounding_traffic",
   torc="Miro 'Concrete Scenario A'",
   desc="SDT changes lane into the gap between B (ahead) and D (behind) in the target lane, with A and C in the origin lane. All actors keep their speed.",
   lc_type="Discretionary", side="left / right",
   actors="A: lead origin lane, constant speed; B: lead target lane, constant speed; C: follower origin lane, constant speed; D: follower target lane, constant speed",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2 (TORC-ODD-356); dashed boundary (TORC-FLD-1588)",
   params="sdt_speed, lc_side, front_gap_target_lane, rear_gap_target_lane, actor_speed_rel_to_sdt (B, D), actor_kind",
   variants="Gap size small / medium / large; D slower / same / faster than SDT",
   wanted="Accept the gap only if front gap to B and rear gap to D are above thresholds that depend on speed and relative speed, and D does not need to brake hard. Otherwise wait, adjust speed to align with a better gap, or stay.",
   tasks="T1, T3, T5, T6, T7, T8, T9, T10",
   cov="front_gap_target_lane [0..6 s, 0.5 s]; rear_gap_target_lane [0..6 s, 0.5 s]; rel_speed_D [-20..+30 mph, 5 mph]; lc_side; actor_kind(D); cross: rear_gap x rel_speed_D",
   kpis="K-SAF-01, K-SAF-02, K-SAF-04, K-SAF-05, K-SAF-06, K-CMP-01, K-CMP-02, K-EFF-01, K-CRT-02",
   mods="M-01, M-02, M-04, M-05, M-06, M-11",
   odd="In-ODD",
   ctx=["Longitudinal speed", "Longitudinal gap", "Lateral clearance", "Signal intent for maneuver", "Lateral control / stay-in-lane"],
   tcs="TC-CRAWL-168, TC-CRAWL-169, TC-CRAWL-173, TC-CRAWL-186, TC-CRAWL-176",
   env="Simulation; public road with Torc lead (B) and chase (D) vehicles",
   fx="sut_cut_out family with target-lane actors added")

sc(id="LC-NOM-03", fam="LC-NOM", name="sut_overtake_slow_lead",
   torc="",
   desc="A is slower than SDT in the origin lane. SDT changes lane, passes A, keeps the target lane or prepares to return.",
   lc_type="Discretionary (efficiency)", side="left (typical)",
   actors="A: slow lead origin lane; B, D optional in target lane",
   phases="approach_slow_lead > signal > change_lane > pass > post_phase",
   static="Lane Count >= 2; left-lane-for-passing signage where present (TC-CRAWL-134)",
   params="sdt_speed, actor_speed_rel_to_sdt (A: -25..-5 mph), distance_to_A_at_decision, front_gap_target_lane, rear_gap_target_lane",
   variants="A is a car / truck / wide load; target lane busy or free",
   wanted="Decide to overtake early enough to avoid hard braking behind A; pass at a safe lateral distance; do not overtake where prohibited.",
   tasks="T1, T3, T4, T5, T6, T7, T8, T9, T10",
   cov="rel_speed_A [-25..-5 mph, 5 mph]; distance_to_A_at_decision [20..200 m, 20 m]; actor_kind(A)",
   kpis="K-SAF-01, K-SAF-02, K-SAF-04, K-CMP-01, K-EFF-01, K-EFF-04",
   mods="M-01, M-02, M-03, M-06, M-11",
   odd="In-ODD",
   ctx=["Longitudinal speed", "Longitudinal gap", "Lateral clearance"],
   tcs="TC-CRAWL-134, TC-CRAWL-187, TC-CRAWL-189, TC-CRAWL-192",
   env="Simulation; track",
   fx="Lead-vehicle family composed with sut_cut_out (lead-vehicle scenario name not verified)")

sc(id="LC-NOM-04", fam="LC-NOM", name="sut_return_lane_after_overtake",
   torc="",
   desc="After passing, SDT returns to the original lane in front of the overtaken vehicle, which is now C in the target lane.",
   lc_type="Discretionary", side="right (typical)",
   actors="D (former A): overtaken vehicle, now behind in the target lane; B optional",
   phases="pass > signal > change_lane_back > post_phase",
   static="Lane Count >= 2",
   params="rear_gap_target_lane (to overtaken vehicle), actor_speed_rel_to_sdt, trailer length",
   variants="Overtaken vehicle accelerates while being passed",
   wanted="Return only when the full combination (tractor and trailer) is clear of the overtaken vehicle with a rear gap above threshold (TX TRC 545.053).",
   tasks="T1, T3, T5, T6, T7, T9, T10",
   cov="rear_gap_target_lane [0..6 s, 0.5 s]; rel_speed_overtaken [-10..+10 mph]",
   kpis="K-SAF-01, K-SAF-05, K-CMP-05, K-CRT-02",
   mods="M-01, M-02, M-05, M-10",
   odd="In-ODD",
   ctx=["Longitudinal gap", "Lateral clearance", "Misleading signal (not needed)"],
   tcs="TC-CRAWL-014, TC-CRAWL-176, TC-CRAWL-186",
   env="Simulation; track",
   fx="Reverse of sut_cut_out (ego returns in front of a vehicle); no public library name verified")

sc(id="LC-TGT-01", fam="LC-TGT", name="sut_lane_change_with_fast_rear_approach",
   torc="",
   desc="D approaches fast in the target lane while SDT prepares or starts the lane change.",
   lc_type="Discretionary", side="left / right",
   actors="D: follower target lane, closing fast; B optional",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2",
   params="rear_closing_speed, rear_gap_target_lane, sdt_speed, actor_kind(D), D appears during prepare vs execute phase",
   variants="D visible early / D emerges from occlusion behind C",
   wanted="Do not start if D would have to brake above threshold; if already started, abort and return when safer than continuing.",
   tasks="T1, T3, T5, T8",
   cov="rear_closing_speed [0..30 mph, 5 mph]; rear_gap_target_lane [0..6 s, 0.5 s]; phase_at_detection [prepare, early execute, late execute]",
   kpis="K-SAF-01, K-SAF-02, K-SAF-05, K-SAF-08, K-CMP-02",
   mods="M-01, M-02, M-04, M-05, M-06, M-10, M-11",
   odd="In-ODD",
   ctx=["Longitudinal gap", "Longitudinal speed", "Lateral clearance"],
   tcs="TC-CRAWL-179, TC-CRAWL-175, TC-CRAWL-186, TC-CRAWL-169",
   env="Simulation; track",
   fx="")

sc(id="LC-TGT-02", fam="LC-TGT", name="sut_lane_change_with_simultaneous_merge_from_far_lane",
   torc="Miro 'Concrete Scenario B' (vehicle E)",
   desc="While SDT changes into the target lane, E in the lane beyond the target lane also changes into the same target lane.",
   lc_type="Discretionary", side="left / right (requires lane_count >= 3)",
   actors="E: far-lane vehicle, starts lane change into target lane; A, B, C, D as in NOM-02; F optional",
   phases="init_drive > signal > change_lane (SDT) || change_lane (E) > resolve > post_phase",
   static="Lane Count >= 3 (TORC-ODD-356: 46.6% of miles)",
   params="actor_lc_start_time_rel_to_sdt (E), E longitudinal offset to SDT, actor_speed_rel_to_sdt (E), actor_lateral_speed (E), E signals or not",
   variants="Miro: E1 holds velocity equal to SDT (side by side); E2 accelerates forward. Added: E3 decelerates, E4 no turn signal",
   wanted="Detect E's intent (signal, lateral drift) early; if conflict, hold or abort and return; never complete the lane change into a space E is entering.",
   tasks="T1, T3, T5, T8",
   cov="E_lc_start_rel_to_sdt [-2..+3 s, 0.5 s]; E_long_offset [-30..+30 m, 5 m]; E_rel_speed [-10..+15 mph]; E_signal [yes, no]; cross: E_offset x E_rel_speed",
   kpis="K-SAF-01, K-SAF-02, K-SAF-04, K-SAF-08, K-CMP-02",
   mods="M-02, M-04, M-05, M-06, M-11",
   odd="In-ODD",
   ctx=["Lateral clearance", "Lane keeping / route guidance", "Signal intent for maneuver"],
   tcs="TC-CRAWL-171, TC-CRAWL-175, TC-CRAWL-181, TC-CRAWL-184, TC-CRAWL-186",
   env="Simulation; public road with Torc lead (B), chase (D) and a controlled E (Miro Concrete B)",
   fx="vehicle_cut_in (E cutting toward SDT lane) composed with sut_cut_out")

sc(id="LC-TGT-03", fam="LC-TGT", name="sut_lane_change_with_closing_gap",
   torc="",
   desc="D accelerates to close the gap while SDT signals or starts the lane change (non-cooperative driver).",
   lc_type="Discretionary", side="left / right",
   actors="D: follower target lane, accelerates after SDT signal; B constant",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2",
   params="D acceleration [0.5..3 m/s2], D reaction delay to SDT signal [0..3 s], rear_gap_target_lane",
   variants="D accelerates during signal phase / during lateral motion",
   wanted="Re-evaluate the gap continuously; abort or delay; do not force D to brake.",
   tasks="T3, T5, T8",
   cov="D_accel [0.5..3 m/s2]; D_reaction_delay [0..3 s]; phase_at_trigger",
   kpis="K-SAF-01, K-SAF-05, K-SAF-08, K-EFF-03",
   mods="M-06",
   odd="In-ODD",
   ctx=["Longitudinal gap", "Lateral clearance"],
   tcs="TC-CRAWL-175, TC-CRAWL-176",
   env="Simulation",
   fx="")

sc(id="LC-TGT-04", fam="LC-TGT", name="sut_lane_change_with_target_lead_braking",
   torc="",
   desc="B brakes while SDT is moving into the target lane behind it.",
   lc_type="Discretionary", side="left / right",
   actors="B: lead target lane, brakes; D behind",
   phases="init_drive > change_lane > B_brake > post_phase",
   static="Lane Count >= 2",
   params="actor_long_decel (B), front_gap_target_lane, phase_at_trigger",
   variants="B brakes mildly / hard; D close behind (no room to brake hard)",
   wanted="Keep a safe gap to B while finishing or aborting; manage braking with D behind (H3 risk).",
   tasks="T1, T3, T8, T9",
   cov="B_decel [1..8 m/s2, 1]; front_gap_target_lane; rear_gap_target_lane; phase_at_trigger",
   kpis="K-SAF-01, K-SAF-02, K-SAF-06, K-SAF-08",
   mods="M-01, M-04, M-05, M-09",
   odd="In-ODD",
   ctx=["Longitudinal speed", "Longitudinal gap"],
   tcs="TC-CRAWL-185, TC-CRAWL-176, TC-CRAWL-039",
   env="Simulation; track",
   fx="Lead-vehicle braking composed with sut_cut_out (name not verified)")

sc(id="LC-TGT-05", fam="LC-TGT", name="sut_lane_change_with_vehicle_alongside_trailer",
   torc="",
   desc="A vehicle travels alongside the SDT trailer in the target lane (D overlapping the combination), partly in the trailer blind zone.",
   lc_type="Discretionary", side="left / right",
   actors="D: in target lane overlapping trailer length",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2",
   params="D longitudinal position along trailer [-25..+5 m from tractor front], actor_speed_rel_to_sdt (D), actor_kind(D)",
   variants="D lingers alongside / slowly passing / slowly falling back",
   wanted="Target lane must be clear over the whole combination length plus margins before any lateral motion.",
   tasks="T1, T5, T7",
   cov="D_long_position_along_trailer [-25..+5 m, 2.5 m]; D_rel_speed [-5..+5 mph]; actor_kind(D)",
   kpis="K-SAF-01, K-SAF-04, K-CMP-02",
   mods="M-01, M-02, M-05, M-10, M-11",
   odd="In-ODD",
   ctx=["Lateral clearance", "Lateral control / stay-in-lane"],
   tcs="TC-CRAWL-014, TC-CRAWL-186, TC-CRAWL-193, TC-CRAWL-012",
   env="Simulation; track",
   fx="")

sc(id="LC-TGT-06", fam="LC-TGT", name="sut_lane_change_with_motorcycle_in_blind_spot",
   torc="",
   desc="A motorcycle is in the target lane in the SDT blind zone or lane-splitting.",
   lc_type="Discretionary", side="left / right",
   actors="D (motorcycle): target lane, beside or behind trailer",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2",
   params="motorcycle position along combination, actor_speed_rel_to_sdt, lateral position in lane",
   variants="Motorcycle steady / accelerating to pass / filtering between lanes",
   wanted="Detect small actors in all side slots; no lateral motion until confirmed clear.",
   tasks="T1, T3, T5",
   cov="moto_long_position [-25..+5 m]; moto_lateral_offset [-1..+1 m]; moto_rel_speed [-5..+20 mph]",
   kpis="K-SAF-01, K-SAF-04",
   mods="M-01, M-04, M-05, M-10",
   odd="In-ODD",
   ctx=["Lateral clearance"],
   tcs="TC-CRAWL-200, TC-CRAWL-201",
   env="Simulation; track with motorcycle target",
   fx="")

sc(id="LC-TGT-07", fam="LC-TGT", name="sut_lane_change_next_to_large_or_unstable_vehicle",
   torc="",
   desc="Target lane contains a wide load or a truck with a swaying trailer next to the gap.",
   lc_type="Discretionary", side="left / right",
   actors="B or D: wide load / swaying trailer / oversize vehicle",
   phases=STD_PHASES_DISC,
   static="Lane Count >= 2; Lane Width (TORC-ODD-76)",
   params="actor_kind, actor lateral excursion amplitude [0..1 m], lane_width",
   variants="Wide load encroaching on boundary; trailer sway under wind",
   wanted="Increase lateral and longitudinal margins or do not change lane next to unstable / oversize vehicles.",
   tasks="T1, T3, T5, T7",
   cov="actor_kind [wide load, swaying trailer, oversize]; lateral_excursion [0..1 m, 0.25 m]; lane_width",
   kpis="K-SAF-01, K-SAF-04",
   mods="M-03, M-08",
   odd="In-ODD",
   ctx=["Lateral clearance"],
   tcs="TC-CRAWL-187, TC-CRAWL-188, TC-CRAWL-189, TC-CRAWL-192, TC-CRAWL-191",
   env="Simulation",
   fx="")

sc(id="LC-CUR-01", fam="LC-CUR", name="sut_lane_change_with_origin_lead_braking",
   torc="",
   desc="A brakes while SDT is preparing or executing the lane change.",
   lc_type="Discretionary becoming urgent", side="left / right",
   actors="A: lead origin lane, brakes; B, D in target lane",
   phases="init_drive > signal > A_brake || change_lane > post_phase",
   static="Lane Count >= 2",
   params="actor_long_decel (A), distance to A, phase_at_trigger, target lane occupancy",
   variants="Target lane free (continue) / occupied (brake in lane)",
   wanted="Choose between completing the lane change and braking in lane based on target-lane state; never get stuck straddling with A braking.",
   tasks="T1, T3, T5, T8, T9",
   cov="A_decel [1..8 m/s2]; distance_to_A [10..80 m]; phase_at_trigger; target_lane_free [yes, no]",
   kpis="K-SAF-01, K-SAF-02, K-SAF-07, K-SAF-08",
   mods="M-01, M-05, M-09",
   odd="In-ODD",
   ctx=["Longitudinal speed", "Front obstacle avoidance", "Longitudinal gap"],
   tcs="TC-CRAWL-185, TC-CRAWL-174, TC-CRAWL-039",
   env="Simulation; track",
   fx="Lead-vehicle braking composed with sut_cut_out (name not verified)")

sc(id="LC-CUR-02", fam="LC-CUR", name="sut_evasive_lane_change_after_lead_cut_out",
   torc="",
   desc="A cuts out and reveals a stopped vehicle or obstacle in the origin lane; SDT must change lane or stop.",
   lc_type="Mandatory (evasive)", side="left / right",
   actors="A: cuts out to target lane; O: stopped vehicle / obstacle in origin lane; D in target lane",
   phases="follow_A > A_cut_out > reveal_O > decide > change_lane or brake",
   static="Lane Count >= 2",
   params="distance to O at reveal, sdt_speed, target lane occupancy, O kind",
   variants="Target lane free / occupied; O is vehicle / debris / crash",
   wanted="Brake first if the target lane is not clear; evasive lane change only with a verified gap.",
   tasks="T1, T3, T4, T5, T8, T9",
   cov="distance_to_O_at_reveal [20..150 m, 10 m]; sdt_speed; target_lane_free",
   kpis="K-SAF-01, K-SAF-02, K-SAF-05, K-SAF-08",
   mods="M-01, M-04, M-05, M-06",
   odd="In-ODD (stopped vehicle in lane: Out-of-ODD when disabled vehicle)",
   ctx=["Front obstacle avoidance", "Longitudinal speed", "Lateral clearance"],
   tcs="TC-CRAWL-182, TC-CRAWL-186, TC-CRAWL-210, TC-CRAWL-174",
   env="Simulation",
   fx="vehicle_cut_out_exposing_vehicle (public Foretellix evaluation scenario)")

sc(id="LC-CUR-03", fam="LC-CUR", name="sut_lane_change_with_tailgating_follower",
   torc="",
   desc="C follows very close behind SDT in the origin lane while SDT prepares a lane change that needs speed adjustment.",
   lc_type="Discretionary", side="left / right",
   actors="C: follower origin lane, short headway; B, D target lane",
   phases="init_drive > adjust_speed > change_lane > post_phase",
   static="Lane Count >= 2",
   params="C headway [0.3..1.5 s], SDT decel needed for gap alignment",
   variants="C also starts to change lane",
   wanted="Prefer gap alignment by acceleration or waiting rather than braking with a tailgater; signal early.",
   tasks="T1, T5, T6, T9",
   cov="C_headway [0.3..1.5 s, 0.1]; sdt_decel_requested [0..3 m/s2]",
   kpis="K-SAF-01, K-SAF-02, K-CRT-02",
   mods="M-04, M-06",
   odd="In-ODD",
   ctx=["Longitudinal speed", "Longitudinal gap", "Signal intent for maneuver"],
   tcs="TC-CRAWL-176, TC-CRAWL-273, TC-CRAWL-274",
   env="Simulation",
   fx="")

sc(id="LC-RD-01", fam="LC-RD", name="sut_mandatory_lane_change_lane_drop",
   torc="",
   desc="The origin lane ends (lane drop / lane ends) and SDT must merge into the adjacent lane with traffic.",
   lc_type="Mandatory (deadline)", side="toward continuing lane",
   actors="B, D in target lane; C behind",
   phases="approach_drop > decide > signal > change_lane > post_phase",
   static="Lane Count change (TORC-ODD-356); merge arrows / signs (TC-CRAWL-079, 140)",
   params="distance_to_mandatory_point, traffic_volume, front_gap_target_lane, rear_gap_target_lane",
   variants="Lane drop signed / unsigned; drop not in map",
   wanted="Plan the lane change early with enough distance to find a gap; adjust speed to create a gap; never reach the end of the lane without a solution (fallback: controlled stop before taper).",
   tasks="T2, T4, T5, T6, T7, T8",
   cov="distance_to_mandatory_point [100..1600 m]; traffic_volume [300..2000 veh/h]; first_feasible_gap_index",
   kpis="K-SAF-01, K-SAF-05, K-CMP-01, K-EFF-01, K-EFF-03",
   mods="M-04, M-05, M-06",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance", "Longitudinal gap", "Lateral clearance"],
   tcs="TC-CRAWL-024, TC-CRAWL-046, TC-CRAWL-047, TC-CRAWL-148, TC-CRAWL-079, TC-CRAWL-140",
   env="Simulation; public road site",
   fx="")

sc(id="LC-RD-02", fam="LC-RD", name="sut_lane_change_in_work_zone_lane_closure",
   torc="",
   desc="Work zone closes a lane with channelizing devices; SDT must merge and follow shifted / temporary lanes.",
   lc_type="Mandatory (deadline)", side="toward open lane",
   actors="B, D in open lane; S: workers / equipment; O: cones, barrels",
   phases="approach_wz > detect_closure > signal > change_lane > follow_shift",
   static="Work Zones (TORC-FLD-1569); temporary markings contradicting permanent markings",
   params="taper distance, temporary vs permanent marking conflict, traffic_volume, worker proximity",
   variants="Closure in map / not in map; night work zone",
   wanted="Follow temporary devices over permanent markings; merge before taper (zipper merge when congested); respect reduced speed.",
   tasks="T1, T2, T4, T5, T6, T7",
   cov="taper_distance; marking_conflict [yes, no]; closure_in_map [yes, no]; light [day, night]",
   kpis="K-SAF-01, K-SAF-04, K-CMP-03, K-EFF-01",
   mods="M-05, M-06",
   odd="In-ODD (Work Zones element present, no values in HD map yet)",
   ctx=["Lane keeping / route guidance", "Lateral clearance", "Longitudinal gap"],
   tcs="TC-CRAWL-240, TC-CRAWL-241, TC-CRAWL-242, TC-CRAWL-243, TC-CRAWL-244, TC-CRAWL-245, TC-CRAWL-238",
   env="Simulation; public road site (Walk scope adds fixed construction zone)",
   fx="")

sc(id="LC-RD-03", fam="LC-RD", name="sut_lane_change_in_weave_section",
   torc="",
   desc="SDT changes lane in a weave section between an on-ramp and an off-ramp with many crossing lane changes.",
   lc_type="Discretionary or mandatory", side="left / right",
   actors="E, F, B, D: vehicles weaving in both directions",
   phases="enter_weave > change_lane > exit_weave",
   static="Weaving Lane (TC-CRAWL-049); Merging Lane",
   params="weave length, number of weaving actors, traffic_volume",
   variants="Short weave; dense weaving traffic",
   wanted="Anticipate crossing lane changes of others; avoid lane change in the shortest part of the weave when possible.",
   tasks="T1, T2, T3, T5",
   cov="weave_length [200..800 m]; weaving_actor_count [0..6]",
   kpis="K-SAF-01, K-SAF-02, K-SAF-04",
   mods="M-06",
   odd="In-ODD",
   ctx=["Lateral clearance", "Longitudinal gap"],
   tcs="TC-CRAWL-049, TC-CRAWL-050, TC-CRAWL-097",
   env="Simulation",
   fx="")

sc(id="LC-RD-04", fam="LC-RD", name="sut_mandatory_lane_change_for_exit",
   torc="",
   desc="SDT must reach the exit lane before the exit; sign may be missed or obscured.",
   lc_type="Mandatory (route)", side="right (typical)",
   actors="B, D in target lane",
   phases="approach_exit > decide > signal > change_lane > post_phase",
   static="Exit/Off-Ramp; interchange guide signs (TC-CRAWL-144, 145)",
   params="distance_to_mandatory_point, traffic_volume, sign visibility",
   variants="Exit sign obscured; late decision",
   wanted="Plan from map, not only from signs; if the gap cannot be found in time, continue past the exit (reroute) rather than force a late lane change.",
   tasks="T2, T4, T5",
   cov="distance_to_exit_at_decision [200..2000 m]; traffic_volume",
   kpis="K-SAF-01, K-SAF-05, K-EFF-01",
   mods="M-04, M-05, M-06",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance", "Longitudinal gap"],
   tcs="TC-CRAWL-101, TC-CRAWL-102, TC-CRAWL-144, TC-CRAWL-145, TC-CRAWL-146, TC-CRAWL-147",
   env="Simulation",
   fx="")

sc(id="LC-RD-05", fam="LC-RD", name="sut_lane_change_to_yield_to_merging_traffic",
   torc="",
   desc="Vehicles enter from an on-ramp next to SDT; SDT moves over to let them merge (courtesy).",
   lc_type="Discretionary (courtesy)", side="left",
   actors="E (ramp vehicle): merging from on-ramp; B, D in target lane",
   phases="approach_ramp > decide > signal > change_lane > post_phase",
   static="Entry/On-Ramp (TC-CRAWL-099, 100)",
   params="ramp vehicle speed rel to SDT, acceleration-lane length, target lane occupancy",
   variants="Target lane busy: adjust speed instead",
   wanted="Move over when the target lane is clear; otherwise adjust speed to let the ramp vehicle merge.",
   tasks="T1, T3, T4, T5",
   cov="ramp_rel_speed [-30..0 mph]; accel_lane_length; target_lane_free",
   kpis="K-SAF-01, K-CRT-03, K-SAF-05",
   mods="M-06",
   odd="In-ODD",
   ctx=["Lateral clearance", "Longitudinal gap"],
   tcs="TC-CRAWL-052, TC-CRAWL-099, TC-CRAWL-100, TC-CRAWL-265",
   env="Simulation; public road site",
   fx="")

sc(id="LC-RD-06", fam="LC-RD", name="sut_lane_change_with_degraded_lane_markings",
   torc="",
   desc="Boundary between origin and target lane is faded, missing, double-exposed or misleading.",
   lc_type="Discretionary", side="left / right",
   actors="none (or NOM-02 traffic)",
   phases=STD_PHASES_DISC,
   static="Lane Boundary (TORC-FLD-1588); Edge Lines",
   params="marking_quality, light, rain",
   variants="Solid line misread as dashed; shadows or skid marks resembling lines",
   wanted="If boundary type or lane count is uncertain, do not change lane unless needed; use map and other vehicles as cues.",
   tasks="T2, T4",
   cov="marking_quality [good, faded, missing, double exposure, shadow]; light; rain",
   kpis="K-SAF-01, K-CMP-03",
   mods="M-01, M-04, M-05",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance", "Lateral control / stay-in-lane"],
   tcs="TC-CRAWL-025, TC-CRAWL-055, TC-CRAWL-060, TC-CRAWL-061, TC-CRAWL-064, TC-CRAWL-065, TC-CRAWL-068",
   env="Simulation; track with modified markings",
   fx="")

sc(id="LC-RD-07", fam="LC-RD", name="sut_lane_change_on_curve_or_grade",
   torc="",
   desc="Lane change on a curve, crest or steep grade where sight distance and stability margins are reduced.",
   lc_type="Discretionary", side="left / right",
   actors="B or D possibly hidden by crest / curve",
   phases=STD_PHASES_DISC,
   static="Curvature (TORC-ODD-360); Slope (TORC-ODD-79); vertical curve",
   params="curvature, grade, sight distance, sdt_speed, load",
   variants="Crest hides B; downhill with heavy load",
   wanted="Avoid lane changes where sight distance is below need; respect stability limits with load.",
   tasks="T1, T5, T7, T9",
   cov="curvature bins; grade [-8..+8 %]; sight_distance [50..400 m]",
   kpis="K-SAF-01, K-SAF-02, K-CRT-01",
   mods="M-03",
   odd="In-ODD",
   ctx=["Vehicle stability", "Lateral control / stay-in-lane", "Longitudinal speed"],
   tcs="TC-CRAWL-032, TC-CRAWL-034, TC-CRAWL-036, TC-CRAWL-039, TC-CRAWL-042, TC-CRAWL-001, TC-CRAWL-006",
   env="Simulation",
   fx="")

sc(id="LC-RD-08", fam="LC-RD", name="sut_lane_change_with_map_lane_mismatch",
   torc="",
   desc="Map and reality disagree on lane count or lane availability (recent restriping, added lane not in map).",
   lc_type="Discretionary", side="left / right",
   actors="none (or NOM-02 traffic)",
   phases=STD_PHASES_DISC,
   static="Map (L6); Lane Count",
   params="map vs reality mismatch type",
   variants="Target lane exists in map but not on road; lane exists on road but not in map",
   wanted="Detect inconsistency; do not change into a lane not confirmed by perception.",
   tasks="T2, T4",
   cov="mismatch_type [lane missing, extra lane, shifted lane]",
   kpis="K-SAF-01, K-CMP-03",
   mods="M-05",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance"],
   tcs="TC-CRAWL-237, TC-CRAWL-238, TC-CRAWL-239, TC-CRAWL-141",
   env="Simulation",
   fx="")

sc(id="LC-ABT-01", fam="LC-ABT", name="sut_lane_change_abort_and_return",
   torc="",
   desc="A trigger (D accelerates, E merges, B brakes) appears after lateral motion started; SDT returns to the origin lane.",
   lc_type="Abort", side="return to origin",
   actors="Trigger actor: D, E or B; C behind in origin lane",
   phases="change_lane > trigger > abort > return > post_phase",
   static="Lane Count >= 2",
   params="lateral progress at trigger [0..100 %], trigger type, C position",
   variants="Trigger before / after point of no return",
   wanted="Abort when continuing is less safe; return with controlled lateral motion; cancel or switch signal; do not oscillate between lanes.",
   tasks="T3, T6, T8, T9",
   cov="lateral_progress_at_trigger [0..100 %, 10 %]; trigger_type [D accel, E merge, B brake]",
   kpis="K-SAF-01, K-SAF-07, K-SAF-08, K-CRT-01",
   mods="M-01, M-03, M-06",
   odd="In-ODD",
   ctx=["Lateral clearance", "Vehicle stability", "Misleading signal (not needed)"],
   tcs="TC-CRAWL-175, TC-CRAWL-171, TC-CRAWL-227",
   env="Simulation",
   fx="")

sc(id="LC-ABT-02", fam="LC-ABT", name="sut_lane_change_interrupted_by_ddt_fallback",
   torc="",
   desc="A system degradation requires MRM while SDT is mid lane change.",
   lc_type="Abort to MRM", side="n/a",
   actors="B, D in target lane; C in origin lane",
   phases="change_lane > degradation > fallback_decision > MRM",
   static="Shoulder Presence (TORC-ODD-81)",
   params="lateral progress at degradation, degradation type, shoulder availability",
   variants="Complete LC then MRM / return then MRM",
   wanted="Never end the MRM straddling two lanes; finish or return depending on progress and traffic, then perform MRM.",
   tasks="T8, T9 (fallback planner)",
   cov="lateral_progress_at_degradation; degradation_type; shoulder_present",
   kpis="K-SAF-01, K-SAF-07, K-SAF-08",
   mods="M-01, M-05",
   odd="In-ODD",
   ctx=["Lane keeping / route guidance", "Longitudinal speed"],
   tcs="TC-CRAWL-232, TC-CRAWL-012, TC-CRAWL-251",
   env="Simulation; fault injection on track",
   fx="")

sc(id="LC-OOD-01", fam="LC-OOD", name="sut_move_over_for_stopped_emv_on_shoulder",
   torc="",
   desc="Stopped EMV, police, TxDOT or tow vehicle with lights on the shoulder; SDT vacates the adjacent lane or slows.",
   lc_type="Mandatory (legal)", side="away from shoulder",
   actors="S: stopped EMV with lights; B, D in target lane",
   phases="approach > detect_emv > decide > change_lane or slow > pass",
   static="Shoulder Presence (TORC-ODD-81)",
   params="detection distance, EMV kind, target lane occupancy, light",
   variants="Target lane busy: slow 20 mph below limit instead",
   wanted="Vacate the lane closest to the EMV when safe, otherwise slow to 20 mph below the posted limit (TX TRC 545.157).",
   tasks="T1, T4, T5, T6",
   cov="detection_distance [50..400 m]; emv_kind; target_lane_free; light",
   kpis="K-SAF-01, K-CMP-04, K-SAF-05",
   mods="M-04, M-05, M-06",
   odd="[Out-of-ODD] (EMV dynamics NA in Jama L4)",
   ctx=["Lateral clearance", "Longitudinal speed"],
   tcs="TC-CRAWL-196, TC-CRAWL-197, TC-CRAWL-198, TC-CRAWL-199, TC-CRAWL-183",
   env="Simulation; track",
   fx="")

sc(id="LC-OOD-02", fam="LC-OOD", name="sut_yield_lane_to_approaching_emv",
   torc="",
   desc="EMV with lights / siren approaches from behind in SDT lane; SDT moves over to let it pass.",
   lc_type="Mandatory (legal)", side="right",
   actors="C: EMV approaching; B, D in target lane",
   phases="detect_emv > decide > signal > change_lane > hold",
   static="Lane Count >= 2",
   params="EMV closing speed, congestion level",
   variants="Congestion: passage must be formed in slow traffic (TC-CRAWL-272)",
   wanted="Yield by moving right and slowing or stopping as needed; do not block the EMV path.",
   tasks="T1, T3, T4, T5",
   cov="emv_closing_speed [10..50 mph]; traffic_volume",
   kpis="K-SAF-01, K-CMP-04",
   mods="M-04, M-06",
   odd="[Out-of-ODD]",
   ctx=["Lateral clearance", "Longitudinal gap"],
   tcs="TC-CRAWL-195, TC-CRAWL-198, TC-CRAWL-272",
   env="Simulation",
   fx="")

sc(id="LC-OOD-03", fam="LC-OOD", name="sut_lane_change_with_object_in_target_lane",
   torc="",
   desc="FOD, lost cargo or an unusual object lies in the target lane at or after the planned merge point.",
   lc_type="Discretionary", side="left / right",
   actors="O: object in target lane",
   phases=STD_PHASES_DISC,
   static="Foreign Object Debris (TORC-ODD-844)",
   params="object size, distance from merge point, object kind",
   variants="Small debris (in ODD) / lost cargo or deformable object (Out-of-ODD)",
   wanted="Check the target lane ahead of the merge point; do not merge onto an obstacle.",
   tasks="T1, T5",
   cov="object_size [0.1..2 m]; distance_from_merge_point [0..150 m]; object_kind",
   kpis="K-SAF-01, K-SAF-02",
   mods="M-01, M-04, M-05",
   odd="In-ODD (FOD) / [Out-of-ODD] (lost cargo)",
   ctx=["Front obstacle avoidance"],
   tcs="TC-CRAWL-210, TC-CRAWL-212, TC-CRAWL-214, TC-CRAWL-215, TC-CRAWL-271",
   env="Simulation; track",
   fx="")

sc(id="LC-OOD-04", fam="LC-OOD", name="sut_lane_change_at_crash_scene",
   torc="",
   desc="Crash scene ahead with responders on foot, emergency lighting, debris and improvised lane closure.",
   lc_type="Mandatory", side="away from closure",
   actors="S / O: responders, vehicles, debris; B, D in open lane",
   phases="approach > detect_scene > decide > change_lane > pass_slow",
   static="Improvised closure (not in map)",
   params="closure position, responder proximity, traffic_volume",
   variants="Closure on left / right / center",
   wanted="Slow early, move away from the scene, follow responder direction, pass at low speed.",
   tasks="T1, T2, T4, T5",
   cov="closure_side; responder_distance_to_lane",
   kpis="K-SAF-01, K-CMP-04",
   mods="M-05, M-06",
   odd="[Out-of-ODD]",
   ctx=["Front obstacle avoidance", "Lateral clearance"],
   tcs="TC-CRAWL-266, TC-CRAWL-174",
   env="Simulation",
   fx="")

GAPS = [
    ("G-01", "Task chain", "Torc has no defined SDT-level tasks (Miro red sticky 'Don't have Tasks'). T1..T10 in this file are a solution-independent proposal to validate with Behavior / Planning teams.", "Validate T1..T10 with Matthieu and the planning team; map to AV3.0 components only after (solution-dependent step)."),
    ("G-02", "L4 kinematics", "Relative speeds, gap distributions, cut-in / merge rates per lane on I-35 are not characterized. Logical ranges for 7 parameters are marked GAP.", "TCDS per-lane speeds (Matthieu), TU enrichment (Marwan), CCTV sampling (Neil)."),
    ("G-03", "Acceptance thresholds", "All KPI thresholds are TBD (same critical gap as ISO 21448 Cl.6 acceptance criteria). Candidate values cited from UN R79 / R157 must be verified before use.", "Decide thresholds with Safety + Behavior teams; link to AVSC00006 metrics claim (EiS Behavior)."),
    ("G-04", "ODD data gaps", "Lane Boundary, Work Zones, Shoulder Presence have no values in the ODD report; Curvature and Slope observed ranges exceed spec ranges.", "Raise with ODD owners; until then these parameters stay proposed."),
    ("G-05", "Foretellix library", "Public Foretellix docs confirm the structure (actors, phases, parameters, coverage with buckets, KPIs) and some scenario names (sut_cut_out, vehicle_cut_in, lead_vehicle_with_cut_in, vehicle_cut_out_exposing_vehicle). The full V-Suite is licensed.", "Check whether Torc has a Foretify / V-Suite license; if yes, map each LC-* scenario to the library scenario and reuse its coverage model."),
    ("G-06", "HFS link", "HFS IDs (HFS-001..138) are linked by key 'Highway x Lane Changes / Overtaking x Hazard' because the HFS workbook was not in the shared folder.", "Add HFS IDs when the HFS file is synced."),
    ("G-07", "HIRE version", "Traceability uses HIRE v1 IDs for Highway Lane Change (61 rows). v2 back-fill did not touch Highway Lane Change, so IDs should be identical.", "Confirm against HIRE v2."),
]
